- name: ensure supervisor is present
  apt: name=supervisor state=present
  sudo: yes

- name: ensure supervisor log folder exists
  file: path={{ supervisor_log_path }} state=directory
  sudo: yes

- name: ensure supervisor program confs exists
  file: path={{ supervisor_conf_path }} state=directory
  sudo: yes

- name: copy programs confs
  copy: src={{ item.file }} dest={{ supervisor_conf_path }}/{{ item.file }}
  with_items: programs
  sudo: yes

- name: add supervisord to init
  command: update-rc.d supervisor defaults
  sudo: yes

- name: ensure supervisord is started
  service: name=supervisor state=started
  sudo: yes

- name: reread supervisor apps
  command: supervisorctl reread
  sudo: yes

- name: update supervisor apps
  command: supervisorctl update
  sudo: yes
